---
  
- name: "Installing Packages"
  package:
    name:
      - jq
      - pipx
      - ntpdate
      - flameshot
      - exiftool
      - btop                # system monitor : https://github.com/aristocratos/btop
      - netcat-traditional
      - mingw-w64
      - ranger # console file-manager
      - rdate
    state: latest
  become: true

- name: "Installing recon tools"
  package:
    name:
      - ffuf
      - nuclei
    state: latest
  become: true

- name: "Installing misc packages for exploitation"
  package:
    name:
      - rlwrap
    state: latest
  become: true


# linPeas and winPEAS: /usr/share/peass/linpeas/  /usr/share/peass/winpeas/
- name: "Installing PEASS"
  package:
    name:
      - peass
    state: latest
  become: true


# linPeas and winPEAS: /usr/share/peass/linpeas/  /usr/share/peass/winpeas/
- name: "Installing BloodHound"
  package:
    name:
      - bloodhound
      - neo4j
    state: latest
  become: true

# Exploit-DB
- name: "Installing Exploit-db"
  package:
    name:
      - exploitdb
    state: latest
  become: true


# Exploit-DB
- name: "Installing evil-winrm"
  package:
    name:
      - evil-winrm
    state: latest
  become: true
