---

# collect fascts only one time, to increase performances
- name: Gather facts
  hosts:  all
  gather_facts: yes

- name: "Customizing Parrot"
  hosts: all
  gather_facts: no
  roles:
    - bootstrap
    - configure-system
    - install-tools
    - configure-logging
    - customize-tmux
    - customize-desktop-mate
    - customize-terminal
    - customize-browser
    - role: gantsign.visual-studio-code
      users:
        - username: "{{ ansible_user_id }}" 
          visual_studio_code_extensions:
            # theme 
            - silofy.hackthebox
            # beautify code 
            - esbenp.prettier-vscode
            # langages
            - ms-python.python
            - yzhang.markdown-all-in-one
            # tools 
            - GitHub.copilot
            - mhutchie.git-graph
            # DevSecOps
            - snyk-security.snyk-vulnerability-scanner
          visual_studio_code_settings_overwrite: true
          visual_studio_code_settings: {
            # UI 
            "workbench.colorTheme": "Hack The Box",
            "editor.wordWrap": "on",
            # Markdown 
            "MarkdownPaste.path": "./images/",
            # python 
            "python.formatting.provider": "black" ,
            # MS Telemetry 
            "telemetry.enableTelemetry": false,
            "telemetry.telemetryLevel": "error",
            "telemetry.enableCrashReporter": false,
            # Workaround required to open VSCode over X11 with X11 Forward
            "window.titleBarStyle": "native"
          }
    - hackscripts

