---

# collect fascts only one time, to increase performances
- name: Gather facts
  hosts:  all
  gather_facts: yes

- name: "Customizing Parrot"
  hosts: all
  gather_facts: no
  roles:
    - hackscripts

