---
# tasks file for devops


- name: "Installing Packages"
  package:
    name:
      - kubernetes-client
      # - kubernetes-helm
    state: latest
  become: true

- ansible.builtin.include_tasks: helm.yaml
