- name: "bash > Copy Custom BashRC"
  copy:
    src: "{{ role_path }}/files/.bash_custom"
    dest: "{{ ansible_env.HOME }}"

- name: "bash > Copy Custom Bash aliases"
  copy:
    src: "{{ role_path }}/files/.bash_aliases"
    dest: "{{ ansible_env.HOME }}"

- name: "bash > Insert include from bashrc"
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    marker: "### {mark} ANSIBLE MANAGED BLOCK"
    insertafter: EOF
    block: |
      if [ -f ~/.bash_aliases ]; then
        . ~/.bash_custom
      fi
