---

- name: "ssh > create user ssh directory"
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    mode: '0740'

- name: "ssh > ssh config file"
  ansible.builtin.copy:
    src: "{{ role_path }}/files/sshconfig"
    dest: "{{ ansible_env.HOME }}/.ssh/config"
    mode: '0440'

