---
- name: "Installing useful github repos"
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.location }}"
  loop:
    - { repo: "https://github.com/Flangvik/SharpCollection", location: "/opt/SharpCollection" }
    # - { repo: "https://github.com/danielmiessler/SecLists", location: "/opt/SecLists" }
  become: true
