---


- name: "apt removals > remove unwanted packages"
  become: true
  apt:
    name: 
      - codium
      - geany
      - htop          # replaced by 'btop'
      - libreoffice
      - vscodium
    state: "absent"
    autoremove: true
