---
- name: "apt > Updating apt repo/cache"
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  become: true


- name: "apt > Upgrade all packages"
  apt: upgrade=yes force_apt_get=yes
  become: true

- name: "apt > install system packages"
  become: true
  apt:
    name: 
      - glances
    state: "present"

